# Experiment Configuration for Blood Discriminator

# Data configuration
data:
  class_names: ['A', 'B', 'AB', 'O']
  n_samples: 1000  # For synthetic data demo
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  random_state: 42

# Model architecture configuration
model:
  input_shape: [224, 224, 3]  # Height, Width, Channels
  num_classes: 4

# Training configuration
training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001

# Traditional ML models configuration
traditional_models:
  random_forest:
    n_estimators: 100
    max_depth: 20
    min_samples_split: 5
    random_state: 42
  
  svm:
    C: 1.0
    kernel: 'rbf'
    gamma: 'scale'
    random_state: 42
  
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5
    random_state: 42
  
  mlp:
    hidden_layer_sizes: [256, 128]
    activation: 'relu'
    learning_rate_init: 0.001
    max_iter: 500
    random_state: 42

# Paths configuration
paths:
  data_dir: 'data/raw'
  processed_dir: 'data/processed'
  models_dir: 'models'
  results_dir: 'data/results'

# Preprocessing configuration
preprocessing:
  img_size: [224, 224]
  normalize: true
  augmentation: true

# Evaluation configuration
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
    - auc_roc
    - confusion_matrix
